version: Project3.Engine.Autorelease-{build}
branches:
  only:
  - master
  - development
skip_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  project: The Creator.sln
  verbosity: minimal
before_package:
- ps: >-
    Copy-Item C:\projects\project3\$env:CONFIGURATION\The-Creator.exe C:\projects\project3\EngineResources\.

    Copy-Item C:\projects\project3\README.md C:\projects\project3\EngineResources\.
artifacts:
- path: EngineResources
  name: Project3
deploy:
- provider: GitHub
  auth_token:
    secure: EQ5OXzpbnU30wLIr7rB1zjqcpBtzgiJCp5087bZSBfSbHheXyJ9FgCDb1jdJtXmd
  artifact: Project3
  draft: true
  force_update: true
  on:
    branch: master
    CONFIGURATION: Release